const products = [
	{
		id: 1,
		category: 'cat1',
		image: 'img/products/2.jpg',
		title: 'Medical mask PM 2.5 95+',
		price: 14,
		quantity: 1,
		stock: 4,
	},
	{
		id: 2,
		category: 'cat2',
		image: 'img/products/4.jpg',
		title: 'Antiseptic HS 0.5',
		price: 57,
		quantity: 1,
		stock: 5,
	},
	{
		id: 3,
		category: 'cat3',
		image: 'img/products/6.jpg',
		title: 'Medical gloves',
		price: 3,
		quantity: 1,
		stock: 12,
	},
	{
		id: 4,
		category: 'cat2',
		image: 'img/products/5.jpg',
		title: 'Hygiene kit',
		price: 89,
		quantity: 1,
		stock: 15,
	},
	{
		id: 5,
		category: 'cat4',
		image: 'img/products/7.jpg',
		title: 'Daily prophylactic kit (7)',
		price: 189,
		quantity: 1,
		stock: 6,
	},
	{
		id: 6,
		category: 'cat1',
		image: 'img/products/1.jpg',
		title: 'Medical mask PM 1.5 65+',
		price: 10,
		quantity: 1,
		stock: 7,
	},
	{
		id: 7,
		category: 'cat4',
		image: 'img/products/8.jpg',
		title: 'PLZT 10',
		price: 2,
		quantity: 1,
		stock: 8,
	},
	{
		id: 8,
		category: 'cat4',
		image: 'img/products/9.jpg',
		title: 'Aspirin',
		price: 0.99,
		quantity: 1,
		stock: 11,
	},
	{
		id: 9,
		category: 'cat1',
		image: 'img/products/3.jpg',
		title: 'Medical mask PM 3.0 80+',
		price: 12,
		quantity: 1,
		stock: 6,
	},
];